CREATE TYPE "RestaurantStatus" AS ENUM ('ACTIVE', 'SUSPENDED');
ALTER TABLE "Restaurant"
  ADD COLUMN "status" "RestaurantStatus" NOT NULL DEFAULT 'ACTIVE',
  ADD COLUMN "menuViews" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "lastActivityAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;